# Alias 
alias ls='ls -CFG'

# Smile PROMPT 
export PS1="\`if [ \$? = 0 ]; then echo \[\e[33m\]-_-\[\e[0m\]; else echo \[\e[31m\]O_O\[\e[0m\]; fi\`[\[\e[35;1m\]\u\[\e[0m\]@\[\e[34;1m\]\h\[\e[0m\]:\[\e[30;1m\]\w\e[0m\]]$ \[\e[0m\]"

export LANG="ja_JP.UTF-8"
export LC_ALL="ja_JP.UTF-8"

